import 'babel-polyfill';
import $ from './jquery-3.3.1.min.js'
import jQuery from './jquery-3.3.1.min.js'
require.context('./src/', false, /\.js$/);

import './src/config.js'
import './dist/variables.js'
import mat4 from './src/Extention/gl-matrix-min.js'

import core from './src/Extention/Initialization.js'
import Application from './src/Function/Application.js'
import Array from './src/Function/Array.js'
import Audio from './src/Function/Audio.js'
import Base from './src/Function/Base.js'
import Battery from './src/Function/Battery.js'
import Browser from './src/Function/Browser.js'
import Cache from './src/Function/Cache.js'
import Canvas from './src/Function/Canvas.js'
import ChromeExtend from './src/Function/ChromeExtend.js'
import Clipboard from './src/Function/Clipboard.js'
import Console from './src/Function/Console.js'
import Cookie from './src/Function/Cookie.js'
import detectAdblock from './src/Function/detectAdblock.js'
import dragDrop from './src/Function/dragDrop.js'
import Effect from './src/Function/Effect.js'
import Element from './src/Function/Element.js'
import Event from './src/Function/Event.js'
import File from './src/Function/File.js'
import Flash from './src/Function/Flash.js'
import Gamepad from './src/Function/Gamepad.js'
import Generator from './src/Function/Generator.js'
import Geo from './src/Function/Geo.js'
import Google from './src/Function/Google.js'
import HarmonicGenerator from './src/Function/HarmonicGenerator.js'
import ID3 from './src/Function/ID3.js'
import Imoticon from './src/Function/Imoticon.js'
import JSON from './src/Function/JSON.js'
import List from './src/Function/List.js'
import Lyrics from './src/Function/Lyrics.js'
import Language from './src/Function/Language.js'
import MediaSession from './src/Function/MediaSession.js'
import MediaSource from './src/Function/MediaSource.js'
import Midi from './src/Function/Midi.js'
import Mobile from './src/Function/Mobile.js'
import Mouse from './src/Function/Mouse.js'
import Notify from './src/Function/Notify.js'
import OptionList from './src/Function/OptionList.js'
import Popup from './src/Function/Popup.js'
import Pagenation from './src/Function/Pagenation.js'
import Promise from './src/Function/Promise.js'
import Radio from './src/Function/Radio.js'
import Request from './src/Function/Request.ts'
import Screen from './src/Function/Screen.js'
import Scroll from './src/Function/Scroll.js'
import Selector from './src/Function/Selector.js'
import SessionStorage from './src/Function/SessionStorage.js'
import ScreenCapture from './src/Function/ScreenCapture.js'
import SimpleCrypto from './src/Function/SimpleCrypto.js'
import SNS from './src/Function/SNS.js'
import Speech from './src/Function/Speech.js'
import Storage from './src/Function/Storage.js'
import StreamObject from './src/Function/StreamObject.js'
import String from './src/Function/String.js'
import System from './src/Function/System.js'
import Time from './src/Function/Time.js'
import Timer from './src/Function/Timer.js'
import URL from './src/Function/URL.js'
import Validate from './src/Function/Validate.js'
import WebDB from './src/Function/WebDB.js'
import WebCam from './src/Function/WebCam.js'
import WebRealbook from './src/Function/WebRealbook.js'
import WebSocket from './src/Function/WebSocket.js'
import XML from './src/Function/XML.js'

import UserMedia from './src/Function/UserMedia.js'
import RTC from './src/Function/RTC.js'

import AudioRecorder from './src/Component/AudioRecorder.ts'
import MediaPlayer from './src/Component/MediaPlayer.ts'